echo ...
echo ... Questo comando serve a rinnovare la chiave ed il certificato di firma utilizzati da spid-saml-check.
echo ... Verrà ora richiesto di inserire la password per la chiave privata di firma, almeno 6 caratteri
echo ... 
openssl req -x509 -sha256 -days 730 -newkey rsa:2048 -keyout spid-saml-check.key -out spid-saml-check.crt
echo ... 
echo ... Ora si dovrà reinserire la password per rimuoverla dalla chiave
echo ...
openssl rsa -in spid-saml-check.key -out spid-saml-check.key
echo ...
echo ... Chiave e certificato di firma sono stati salvati rispettivamente in spid-saml-check.key e spid-saml-check.crt
openssl pkey -in spid-saml-check.key -out spid-saml-check.pem -traditional
 